Homework 2 completed
alenasidorova1111/AlenaSidorova pull request #2
Opened 2021-08-09 15:44 UTC by alenasidorova1111

2021-08-12 17:05 UTC, shoggy requested changes
0 test is run, should be 2
I put comments for Ex1, but ex2 needs same changes

2021-08-12 17:05 UTC, shoggy commented on pom.xml
> +            <id>github-page-test-ex1-ex2-tests</id>
Please make this profile active by default

2021-08-12 17:05 UTC, shoggy commented on pom.xml
> +            <version>4.4.3</version>
Please move version to the `properties` section

2021-08-12 17:05 UTC, shoggy commented on pom.xml
> +        </dependency>
Good candidate for `test` scope

2021-08-12 17:05 UTC, shoggy commented on src/test/java/com/epam/tc/hw2/WebdriverSettings.java
> +public class WebdriverSettings {
Please choose appropriate name for this class. Because `Test extends Settings` looks unnatural

2021-08-12 17:05 UTC, shoggy commented on src/test/java/com/epam/tc/hw2/WebdriverSettings.java
> +    protected SoftAssertions soft;
SoftAssert is detail of specific test method, not test class

2021-08-12 17:05 UTC, shoggy commented on src/test/java/com/epam/tc/hw2/WebdriverSettings.java
> +        WebDriverManager.chromedriver().driverVersion("92.0.4515.107").setup();
Why do you use a specific version here?

2021-08-12 17:05 UTC, shoggy commented on src/test/java/com/epam/tc/hw2/ex1/GithubPageSeleniumTestsEx1.java
> +        soft.assertThat(menuTabs.size()).isEqualTo(4);
Selector type precedence order violation. Please use following order: DOM, CSS, XPath

2021-08-12 17:05 UTC, shoggy commented on src/test/java/com/epam/tc/hw2/ex1/GithubPageSeleniumTestsEx1.java
> +        soft.assertThat(menuTabs.get(3).getText()).isEqualTo("METALS & COLORS");
Please combine this to one assertion (collections equality)
\+ same for other occurrences

2021-08-12 17:05 UTC, shoggy commented on src/test/java/com/epam/tc/hw2/ex1/GithubPageSeleniumTestsEx1.java
> +            By.xpath("//ul[@class='uui-navigation nav navbar-nav m-l8'][1]/li"));
`wait.until` returns found elements, no need to call `.findelements` twice
\+ same for other occurrences

2021-08-12 17:05 UTC, shoggy commented on src/test/java/com/epam/tc/hw2/ex1/GithubPageSeleniumTestsEx1.java
> +        soft.assertThat(images.size()).isEqualTo(4);
Please use a specific matcher for collection size
```suggestion
        soft.assertThat(images).hasSize(4);
```

2021-08-12 17:05 UTC, shoggy commented on src/test/resources/testng/test.GithubPageSeleniumEx1Ex2
> +<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd" >
Please add `.xml` extension to the file name

2021-08-13 06:43 UTC, alenasidorova1111 commented on src/test/java/com/epam/tc/hw2/WebdriverSettings.java
> +        WebDriverManager.chromedriver().driverVersion("92.0.4515.107").setup();
That's a recommendation of WebDriverManager ([main] INFO io.github.bonigarcia.wdm.WebDriverManager - Using chromedriver 92.0.4515.107 (resolved driver for Chrome 92))

2021-08-17 10:12 UTC, shoggy commented on src/test/java/com/epam/tc/hw2/WebdriverSettings.java
> +        WebDriverManager.chromedriver().driverVersion("92.0.4515.107").setup();
Looks like only an info message, but not recommendation
As far as I remember, webdrivermanager decides driver version matching existing browser

2021-08-17 15:13 UTC, shoggy requested changes

2021-08-17 15:13 UTC, shoggy commented on src/test/java/com/epam/tc/hw2/ex1/GithubPageSeleniumTestsEx1.java
> +            webDriver.findElements(By.xpath("//ul[@class='uui-navigation nav navbar-nav m-l8'][1]/li"))));
css is preferable over xpath
```suggestion
            webDriver.findElements(By.css("header ul.navbar-nav.m-l8 > li"))));
```

2021-08-17 15:13 UTC, shoggy commented on src/test/java/com/epam/tc/hw2/ex1/GithubPageSeleniumTestsEx1.java
> +    protected SoftAssertions soft;
Convert to local variable

2021-08-17 15:13 UTC, shoggy commented on src/test/java/com/epam/tc/hw2/ex1/GithubPageSeleniumTestsEx1.java
> +            .containsExactlyElementsOf(Arrays.asList("HOME", "CONTACT FORM", "SERVICE", "METALS & COLORS"));
Please define the expected list as a separate variable (in other places too)

2021-08-23 21:16 UTC, shoggy approved these changes

2021-08-23 21:18 UTC, merged